
language: ruby
rvm:
  - ruby-2.2.3

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
  - bundle install
  - export RAILS_ENV=test
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate RAILS_ENV=test
script:
  - bundle exec rake
bundler_args: "--without development"
cache:
  - bundler
notifications:
  email: false