
language: ruby
rvm:
  - ruby-2.2.3

install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt5webkit5-dev
  - bundle install
  - export RAILS_ENV=test
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rake
bundler_args: "--without development"
cache:
  - bundler
notifications:
  email: false